# Generated by Django 3.2.25 on 2025-08-21 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('tipo_documento', models.CharField(choices=[('nota_venta', 'Nota de Venta'), ('factura', 'Factura'), ('orden_trabajo', 'Orden de Trabajo'), ('nota_pedido', 'Nota de Pedido'), ('otros', 'Otros')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('documento_respaldo', models.TextField(blank=True, null=True)),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='documento_soporte/')),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.IntegerField()),
                ('cantidad_recibida', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(choices=[('guia_remision', 'Guia de Remision'), ('guia_servientrega', 'Guia Servientrega'), ('orden_trabajo', 'Orden de Trabajo'), ('otros', 'Otros')], max_length=20)),
                ('documento_respaldo', models.TextField(blank=True, null=True)),
                ('documento_soporte', models.FileField(blank=True, null=True, upload_to='documento_soporte/')),
                ('movimiento_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslado_entrada', to='inventario.movimientoinventario')),
                ('movimiento_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslado_salida', to='inventario.movimientoinventario')),
            ],
        ),
    ]
