# Generated by Django 3.2.25 on 2025-08-25 03:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de 3 caracteres (letras y números)', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{3}$', 'El código debe ser exactamente 3 caracteres alfanuméricos')])),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de 3 caracteres (letras y números)', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{3}$', 'El código debe ser exactamente 3 caracteres alfanuméricos')])),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='categorias.categoria')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de 3 caracteres (letras y números)', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{3}$', 'El código debe ser exactamente 3 caracteres alfanuméricos')])),
                ('nombre', models.CharField(max_length=255)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='categorias.subcategoria')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
