# Generated by Django 3.2.25 on 2025-08-25 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='usuarios.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('codigo', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('codigo', 'subcategoria')},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('codigo', 'empresa')},
        ),
    ]
